modLoader="javafml"
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="pubgmc"
version="0.1-1.14.4"
displayName="PUBGMC Mod"
# updateJSONURL="http://myurl.me/"
# displayURL="http://example.com/"
credits="Thanks OfficialMajonaise for making awesome weapon models; Tomano123 for extensive mod testing and reporting many bugs"
authors="Toma, OfficialMajonaise"
description='''
Description here
'''

[[mods]]
modId="configlib"
version="1.0"
displayName="Toma's Config Library"
authors="Toma"
description='''
This is config library based on .json format

Supports multiple objects, collections and better general design

Made as much user friendly as possible, same applies for devs
'''

[[dependencies.pubgmc]]
    modId="configlib"
    mandatory=true
    versionRange="[1.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.pubgmc]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.pubgmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
