modLoader="javafml"
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="pubgmc"
version="0.1-1.14.4"
displayName="PUBGMC Mod"
# updateJSONURL="http://myurl.me/"
# displayURL="http://example.com/"
credits="Thanks OfficialMajonaise for making awesome weapon models; Tomano123 for extensive mod testing and reporting many bugs"
authors="Toma, OfficialMajonaise"
description='''
Description here
'''

[[dependencies.pubgmc]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.23,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pubgmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
