package dev.toma.pubgmc.init;

import dev.toma.pubgmc.Pubgmc;
import dev.toma.pubgmc.common.item.gun.GunItem;
import dev.toma.pubgmc.common.item.gun.attachment.AttachmentItem;
import dev.toma.pubgmc.common.item.healing.HealingItem;
import dev.toma.pubgmc.common.item.utility.*;
import dev.toma.pubgmc.common.item.wearable.BulletProofArmor;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(Pubgmc.MODID)
public class PMCItems {
    public static final HealingItem BANDAGE = null;
    public static final HealingItem FIRST_AID_KIT = null;
    public static final HealingItem MEDKIT = null;
    public static final HealingItem ENERGY_DRINK = null;
    public static final HealingItem PAINKILLERS = null;
    public static final HealingItem ADRENALINE_SYRINGE = null;
    public static final BulletProofArmor BASIC_HELMET = null;
    public static final BulletProofArmor BASIC_VEST = null;
    public static final BulletProofArmor POLICE_HELMET = null;
    public static final BulletProofArmor POLICE_VEST = null;
    public static final BulletProofArmor MILITARY_HELMET = null;
    public static final BulletProofArmor MILITARY_VEST = null;
    public static final ParachuteItem PARACHUTE = null;
    public static final ThrowableItem GRENADE = null;
    public static final ThrowableItem SMOKE = null;
    public static final ThrowableItem FLASH = null;
    public static final ThrowableItem MOLOTOV = null;
    public static final VehicleSpawnerItem SPAWN_UAZ = null;
    public static final VehicleSpawnerItem SPAWN_GLIDER = null;
    public static final FuelCanItem FUEL_CAN = null;
    public static final AmmoItem CROSSBOW_BOLT = null;
    public static final AmmoItem AMMO_12G = null;
    public static final AmmoItem AMMO_9MM = null;
    public static final AmmoItem AMMO_45ACP = null;
    public static final AmmoItem AMMO_556MM = null;
    public static final AmmoItem AMMO_762MM = null;
    public static final AmmoItem AMMO_300M = null;
    public static final AttachmentItem.Barrel SHOTGUN_CHOKE = null;
    public static final AttachmentItem.Barrel SUPPRESSOR_SMG = null;
    public static final AttachmentItem.Barrel COMPENSATOR_SMG = null;
    public static final AttachmentItem.Barrel SUPPRESSOR_AR = null;
    public static final AttachmentItem.Barrel COMPENSATOR_AR = null;
    public static final AttachmentItem.Barrel SUPPRESSOR_SR = null;
    public static final AttachmentItem.Barrel COMPENSATOR_SR = null;
    public static final AttachmentItem.Grip ANGLED_GRIP = null;
    public static final AttachmentItem.Grip VERTICAL_GRIP = null;
    public static final AttachmentItem.Magazine QUICKDRAW_SMG = null;
    public static final AttachmentItem.Magazine EXTENDED_SMG = null;
    public static final AttachmentItem.Magazine QUICKDRAW_EXTENDED_SMG = null;
    public static final AttachmentItem.Magazine QUICKDRAW_AR = null;
    public static final AttachmentItem.Magazine EXTENDED_AR = null;
    public static final AttachmentItem.Magazine QUICKDRAW_EXTENDED_AR = null;
    public static final AttachmentItem.Magazine QUICKDRAW_SR = null;
    public static final AttachmentItem.Magazine EXTENDED_SR = null;
    public static final AttachmentItem.Magazine QUICKDRAW_EXTENDED_SR = null;
    public static final AttachmentItem.Stock FOLDING_STOCK = null;
    public static final AttachmentItem.Stock TACTICAL_STOCK = null;
    public static final AttachmentItem.Stock CHEEKPAD = null;
    public static final AttachmentItem.Stock BULLET_LOOPS = null;
    public static final AttachmentItem.Scope RED_DOT = null;
    public static final AttachmentItem.Scope HOLOGRAPHIC = null;
    public static final AttachmentItem.Scope X2_SCOPE = null;
    public static final AttachmentItem.Scope X3_SCOPE = null;
    public static final AttachmentItem.Scope X4_SCOPE = null;
    public static final AttachmentItem.Scope X6_SCOPE = null;
    public static final AttachmentItem.Scope X8_SCOPE = null;
    public static final AttachmentItem.Scope X15_SCOPE = null;
    public static final GunItem P92 = null;
}
