package dev.toma.pubgmc.init;

import dev.toma.pubgmc.Pubgmc;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(Pubgmc.MODID)
public class PMCSounds {
    public static final SoundEvent STUN_EFFECT = null;
    public static final SoundEvent STUN_EFFECT_SHORT = null;
    public static final SoundEvent P92_SHOOT = null;
    public static final SoundEvent P92_SHOOT_SILENT = null;
    public static final SoundEvent P92_RELOAD = null;
    public static final SoundEvent P92_RELOAD_FAST = null;
    public static final SoundEvent P1911_SHOOT = null;
    public static final SoundEvent P1911_SHOOT_SILENT = null;
    public static final SoundEvent P1911_RELOAD = null;
    public static final SoundEvent P1911_RELOAD_FAST = null;
    public static final SoundEvent P18C_SHOOT = null;
    public static final SoundEvent P18C_SHOOT_SILENT = null;
    public static final SoundEvent P18C_RELOAD = null;
    public static final SoundEvent P18C_RELOAD_FAST = null;
    public static final SoundEvent DEAGLE_SHOOT = null;
    public static final SoundEvent DEAGLE_RELOAD = null;
    public static final SoundEvent DEAGLE_RELOAD_FAST = null;
    public static final SoundEvent R1895_SHOOT = null;
    public static final SoundEvent R1895_SHOOT_SILENT = null;
    public static final SoundEvent R1895_RELOAD = null;
    public static final SoundEvent R45_SHOOT = null;
    public static final SoundEvent R45_RELOAD = null;
    public static final SoundEvent SCORPION_SHOOT = null;
    public static final SoundEvent SCORPION_SHOOT_SILENT = null;
    public static final SoundEvent SCORPION_RELOAD = null;
    public static final SoundEvent SCORPION_RELOAD_FAST = null;
    public static final SoundEvent SAWED_OFF_SHOOT = null;
    public static final SoundEvent SAWED_OFF_RELOAD = null;
    public static final SoundEvent S1897_SHOOT = null;
    public static final SoundEvent S1897_RELOAD = null;
    public static final SoundEvent S1897_RELOAD_FAST = null;
    public static final SoundEvent S1897_CHAMBER = null;
    public static final SoundEvent S686_SHOOT = null;
    public static final SoundEvent S686_RELOAD = null;
    public static final SoundEvent S686_RELOAD_FAST = null;
    public static final SoundEvent S12K_SHOOT = null;
    public static final SoundEvent S12K_SHOOT_SILENT = null;
    public static final SoundEvent S12K_RELOAD = null;
    public static final SoundEvent S12K_RELOAD_FAST = null;
    public static final SoundEvent UZI_SHOOT = null;
    public static final SoundEvent UZI_SHOOT_SILENT = null;
    public static final SoundEvent UZI_RELOAD = null;
    public static final SoundEvent UZI_RELOAD_FAST = null;
    public static final SoundEvent MP5K_SHOOT = null;
    public static final SoundEvent MP5K_SHOOT_SILENT = null;
    public static final SoundEvent MP5K_RELOAD = null;
    public static final SoundEvent MP5K_RELOAD_FAST = null;
    public static final SoundEvent VECTOR_SHOOT = null;
    public static final SoundEvent VECTOR_SHOOT_SILENT = null;
    public static final SoundEvent VECTOR_RELOAD = null;
    public static final SoundEvent VECTOR_RELOAD_FAST = null;
    public static final SoundEvent PP19_SHOOT = null;
    public static final SoundEvent PP19_SHOOT_SILENT = null;
    public static final SoundEvent PP19_RELOAD = null;
    public static final SoundEvent UMP45_SHOOT = null;
    public static final SoundEvent UMP45_SHOOT_SILENT = null;
    public static final SoundEvent UMP45_RELOAD = null;
    public static final SoundEvent UMP45_RELOAD_FAST = null;
    public static final SoundEvent THOMPSON_SHOOT = null;
    public static final SoundEvent THOMPSON_SHOOT_SILENT = null;
    public static final SoundEvent THOMPSON_RELOAD = null;
    public static final SoundEvent THOMPSON_RELOAD_FAST = null;
    public static final SoundEvent UAZ_IDLE = null;
    public static final SoundEvent UAZ_ACCELERATE = null;
    public static final SoundEvent UAZ_BRAKE = null;
    public static final SoundEvent UAZ_CRUISE = null;
    public static final SoundEvent GLIDER_IDLE = null;
    public static final SoundEvent GLIDER_ACCELERATE = null;
    public static final SoundEvent GLIDER_BRAKE = null;
    public static final SoundEvent GLIDER_CRUISE = null;
}
